branches:
  only:
    - master

before_install:
  - .travis/before_install.sh
  - nvm install 8
  - node --version
  - npm install -g yarn react-native-cli

matrix:
  include:
    # iOS builds
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      env: LANE=ios
      before_install:
        - brew install getsentry/tools/sentry-cli
        - gem install fastlane --no-rdoc --no-ri --no-document --quiet
        - (cd ios; pod install --repo-update; cd -)

    # Android builds
    - language: android
      env: LANE=android
      before_install:
        - gem install fastlane --no-rdoc --no-ri --no-document --quiet

    # CodePush builds
    - os: linux
      env: LANE=js
      before_install:
        - npm install -g code-push-cli

install:
  - yarn install

script:
  - npm run lint
  - npm run test
  - .travis/build.sh