branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  include:
    # iOS builds
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      env: LANE=ios
      before_install:
        - nvm install 8

    # Android builds
    - language: android
      env: LANE=android
      android:
        components:
          - tools
          - platform-tools
          - build-tools-23.0.1
          - build-tools-25.0.2
          - build-tools-25.0.3
          - android-23
          - android-25
          - android-26
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
        licenses:
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      before_install:
        - nvm install 8

    # CodePush builds
    - language: javascript
      env: LANE=js
      node_js:
        - "8"

install:
  - .travis/install.sh

script:
  - .travis/build.sh