branches:
  only:
    - master

matrix:
  include:
    # iOS builds
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      env: LANE=ios
      before_install:
        - nvm install 8
        - node --version

    # Android builds
    - language: android
      env: LANE=android
      android:
        components:
          - build-tools-25.0.3
          - android-26
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
        licenses:
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      before_install:
        - nvm install 8
        - node --version

    # CodePush builds
    - language: javascript
      env: LANE=js
      node_js:
        - "8"
      before_install:
        - nvm install 8
        - node --version

install:
  - .travis/before_install.sh

script:
  - .travis/build.sh